version: "3"
services:
  nacos:
    hostname: nacos
    image: registry.cn-beijing.aliyuncs.com/xfguo/test/nacos/nacos-server:latest
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    ports:
      - "8848:8848"

  #  currency-mysql:
  #    image: mysql:5.6
  #    ports:
  #      - 3306
  #    command: [
  #      --character-set-server=utf8mb4,
  #      --collation-server=utf8mb4_unicode_ci
  #    ]
  #    environment:
  #      MYSQL_ROOT_PASSWORD: currencyservice
  #      MYSQL_DATABASE: currency

  checkout-mysql:
    image: registry.cn-beijing.aliyuncs.com/xfguo/test/mysql:5.6
    ports:
      - 3306
    command: [
      --character-set-server=utf8mb4,
      --collation-server=utf8mb4_unicode_ci
    ]
    environment:
      MYSQL_ROOT_PASSWORD: checkoutservice
      MYSQL_DATABASE: checkout

  product-mysql:
    image: registry.cn-beijing.aliyuncs.com/xfguo/test/mysql:5.6
    ports:
      - 3306
    command: [
      --character-set-server=utf8mb4,
      --collation-server=utf8mb4_unicode_ci
    ]
    environment:
      MYSQL_ROOT_PASSWORD: productservice
      MYSQL_DATABASE: product

  cart-redis:
    image: registry.cn-beijing.aliyuncs.com/xfguo/test/redis:latest
    ports:
      - 6379:6379

  frontend:
    build: ./src/frontend
    image: registry-vpc.cn-beijing.aliyuncs.com/xiaofeng-gxf/frontend:1.1.1-SNAPSHOT
    container_name: frontend
    #    restart: always
    environment:
      - dubbo.registry.address=nacos://nacos-server:8848
      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
      - spring.cloud.nacos.config.server-addr=nacos-server:8848
    ports:
      - "8080:8080"
    depends_on:
      - "nacos"

  cartservice:
    build: ./src/cartservice
    image: registry-vpc.cn-beijing.aliyuncs.com/xiaofeng-gxf/cartservice:1.1.1-SNAPSHOT
    container_name: cartservice
    environment:
      - dubbo.registry.address=nacos://nacos-server:8848
      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
      - spring.cloud.nacos.config.server-addr=nacos-server:8848
    depends_on:
      - "nacos"
      - "cart-redis"

  checkoutservice:
    build: ./src/checkoutservice
    image: registry-vpc.cn-beijing.aliyuncs.com/xiaofeng-gxf/checkoutservice:1.1.1-SNAPSHOT
    container_name: checkoutservice
    environment:
      - dubbo.registry.address=nacos://nacos-server:8848
      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
      - spring.cloud.nacos.config.server-addr=nacos-server:8848
    depends_on:
      - "nacos"
      - "checkout-mysql"

  prdoctservice:
    build: ./src/productservice
    image: registry-vpc.cn-beijing.aliyuncs.com/xiaofeng-gxf/productservice:1.1.1-SNAPSHOT
    container_name: productservice
    environment:
      - dubbo.registry.address=nacos://nacos-server:8848
      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
      - spring.cloud.nacos.config.server-addr=nacos-server:8848
    depends_on:
      - "nacos"
      - "product-mysql"

#  adservice:
#    build: ./src/adservice
#    image: adservice:1.0.0-SNAPSHOT
#    container_name: adservice
#    environment:
#      - dubbo.registry.address=nacos://nacos-server:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
#    depends_on:
#      - "nacos"
#
#
#
#  currencyservice:
#    build: ./src/productservice
#    image: currencyservice:1.0.0-SNAPSHOT
#    container_name: currencyservice
#    environment:
#      - dubbo.registry.address=nacos://nacos-server:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
#    depends_on:
#      - "nacos"
#
#  emailservice:
#    build: ./src/emailservice
#    image: emailservice:1.0.0-SNAPSHOT
#    container_name: emailservice
#    environment:
#      - dubbo.registry.address=nacos://nacos-server:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
#    depends_on:
#      - "nacos"
#
#  paymentservice:
#    build: ./src/paymentservice
#    image: paymentservice:1.0.0-SNAPSHOT
#    container_name: paymentservice
#    environment:
#      - dubbo.registry.address=nacos://nacos-server:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
#    depends_on:
#      - "nacos"
#
#  recomendationservice:
#    build: ./src/recomendationservice
#    image: recomendationservice:1.0.0-SNAPSHOT
#    container_name: recomendationservice
#    environment:
#      - dubbo.registry.address=nacos://nacos-server:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
#    depends_on:
#      - "nacos"
#
#  shippingservice:
#    build: ./src/shippingservice
#    image: shippingservice:1.0.0-SNAPSHOT
#    container_name: shippingservice
#    environment:
#      - dubbo.registry.address=nacos://nacos-server:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
#      - spring.cloud.nacos.discovery.server-addr=nacos-server:8848
#    depends_on:
#      - "nacos"