# Default values for microservice-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cartservice:
  name: cartservice
  image: cartservice:1.0.0-SNAPSHOT

productservice:
  name: productservice
  image: productservice:1.1.0-SNAPSHOT

nacos:
  name: nacos-standalone
  image: nacos/nacos-server:latest
  port: 8848
  host: nacos-standalone

frontend:
  name: frontend
  image: frontend:1.0.0-SNAPSHOT
  port: 8080

checkoutservice:
  name: checkoutservice
  image: checkoutservice:1.0.0-SNAPSHOT


slb:
  zuul: 127.0.0.1

# 接入 mse 时的应用名前缀
application:
  name:
    prefix: demo-


# 各组件的镜像版本号
images:
  version: 0.1-SNAPSHOT

# 默认选择时使用 K8s 里拉起的 Nacos ，也可以填写成 MSE 里购买的 nacos
mse:
  address:
    springcloud: nacos-server:8848
    dubbo: nacos://nacos-server:8848
