# Default values for microservice-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cartservice:
  name: cartservice
  image: cartservice:1.0.0-SNAPSHOT

productservice:
  name: productservice
  image: productservice:1.0.0-SNAPSHOT

nacos:
  name: nacos-standalone
  image: nacos/nacos-server:latest
  port: 8848
  host: nacos-standalone

frontend:
  name: frontend
  image: frontend:1.0.0-SNAPSHOT
  port: 8080

checkoutservice:
  name: checkoutservice
  image: checkoutservice:1.0.0-SNAPSHOT

## 修改成你的 SLB IP
slb:
  zuul: 127.0.0.1

application:
  name:
    prefix: yizhan-

images:
  version: 0.1-SNAPSHOT

mse:
  address:
    springcloud: nacos-server:8848
    dubbo: nacos://nacos-server:8848
