# 镜像地址的前缀
registry: registry.cn-hangzhou.aliyuncs.com/mse-governance-demo/

images:
  version: 3.0.8-sb3-jdk21

# 是否启动zuul、springcloud网关
gateway:
  zuul: false
  springcloud: true
  mse:
    ingress: false

prometheus:
  enable: false

nacos:
  # Nacos地址
  host: nacos-server
  # 注册到Nacos的命名空间id
  namespace: public

autoscaling: false

resources:
  enable: true
  request:
    cpu: 1
    memory: 2Gi
  limit:
    cpu: 1
    memory: 2Gi
